- hosts: all

  vars_files:
    - builder_vars.yml

  tasks:

    - name: Install go
      win_chocolatey:
        name: golang
        state: present
# https://ci.appveyor.com/project/Datadog/datadog-agent/branch/master
        version: '1.10.4'

    - name: Install go
      win_chocolatey:
        name: dep
        state: present

    - name: Install python2
      win_chocolatey:
        name: python2
        state: present
        version: '2.7.15'

    - name: Install python2
      win_chocolatey:
        name: vcpython27
        state: present

    - name: Install Mingw
      win_chocolatey:
        name: mingw
        state: present
        version: '8.1.0'

    - name: Install vcredist-all
      win_chocolatey:
        name: vcredist-all
        state: present

    # choco install ruby --version 2.4.3.1
    - name: Install ruby 2.4.3.1
      win_chocolatey:
        name: ruby
        state: present
        version: 2.4.3.1

    - name: Install ruby2.devkit
      win_chocolatey:
        name: ruby2.devkit
        state: present

    - name: Install python virtualwrapper
      win_shell: pip install virtualenvwrapper-win
      args:
        executable: cmd

    - name: Support for Makefiles
      win_chocolatey:
        name: make
        state: present

    - name: Install awscli
      win_chocolatey:
        name: awscli
        state: present

    - name: Fix spotted bundler issue
      win_shell: gem update --system 2.3.0
      args:
        executable: cmd

    - name: Tune git config
      win_shell: git config –global http.sslcainfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"
      args:
        executable: cmd

    - name: Tune git config
      win_shell: git config –global user.email "gitlab@windows.runner.local"
      args:
        executable: cmd

    - name: Tune git config
      win_shell: git config –global user.name "Windows Gitlab Runner"
      args:
        executable: cmd




