- hosts: all

  vars_files:
    - builder_vars.yml

  tasks:

    - name: Install go
      win_chocolatey:
        name: golang
        state: present
        version: '1.11.4'

    - name: Install python2
      win_chocolatey:
        name: python2
        state: present
        version: '2.7.15'

    - name: Install python2
      win_chocolatey:
        name: vcpython27
        state: present

    - name: Install Mingw
      win_chocolatey:
        name: mingw
        state: present
        version: '8.1.0'

    - name: Install Mingw
      win_chocolatey:
        name: mingw
        state: present

    - name: Install ruby 2.4.3.1
      win_chocolatey:
        name: ruby
        state: present
        version: 2.4.3.1

    - name: Install ruby2.devkit
      win_chocolatey:
        name: ruby2.devkit
        state: present

    - name: Install python virtualwrapper
      win_shell: pip install virtualenvwrapper-win
      args:
        executable: cmd

    - name: Tune git config
      win_shell: git config –global http.sslcainfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"
      args:
        executable: cmd


