apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "trace-java-demo.labels-db" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    {{- include "trace-java-demo.selectorLabels-db" . | nindent 4 }}
