apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trace-java-demo.fullname" . }}-authorsapp
  labels:
    {{- include "trace-java-demo.labels-authorsapp" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "trace-java-demo.selectorLabels-authorsapp" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trace-java-demo.selectorLabels-authorsapp" . | nindent 8 }}
    spec:
      containers:
        - name: authors-app
          image: quay.io/stackstate/trace-java-demo:authors-app-master
          imagePullPolicy: Always
{{/*          command: ["tail","-f","/dev/null"]*/}}
          ports:
            - containerPort: 8081
              name: authors-app
              protocol: TCP
          env:
            - name: MAVEN_OPTS
              value: "-Dsts.service.name=stackstate-demo-cluster:authors-app -Dsts.agent.host=localhost -Dsts.agent.port=8126 -Dstackstate.slf4j.simpleLogger.defaultLogLevel=debug -javaagent:/sts-java-agent.jar"
        - name: traceagent-sidecar
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "trace-java-demo.fullname" . }}-tracemap
          image: "{{ .Values.traceagent_image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8126
              protocol: TCP
      hostPID: true
        {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
