apiVersion: v1
kind: Service
metadata:
  name: books-app
  labels:
  {{- include "trace-java-demo.labels-booksapp" . | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: books-app
  selector:
  {{- include "trace-java-demo.selectorLabels-booksapp" . | nindent 4 }}