- hosts: all

  vars_files:
    - builder_vars.yml

  tasks:

    - name: Install conemu
      win_chocolatey:
        name: conemu
        state: present

    - name: Install go
      win_chocolatey:
        name: golang
        state: present
# https://ci.appveyor.com/project/Datadog/datadog-agent/branch/master
        version: '1.10.4'

    - name: Install go dep
      win_chocolatey:
        name: dep
        state: present

    - name: Install system python2
      win_chocolatey:
        name: python2
        state: present
        version: '2.7.14'
        package_params: "/InstallDir:c:\\python27-x64"

    - name: Install vcpython27
      win_chocolatey:
        name: vcpython27
        state: present
      ignore_errors: true
      register: vcpython27_try1

    - name: Install vcpython27
      win_chocolatey:
        name: vcpython27
        state: present
      when: vcpython27_try1 is failed

#    - name: Install vcredist-all
#      win_chocolatey:
#        name: vcredist-all
#        state: present

    # choco install ruby --version 2.4.3.1
    - name: Install ruby 2.4.3.1
      win_chocolatey:
        name: ruby
        state: present
        version: 2.4.3.1

    # - name: Install Mingw
    #   win_chocolatey:
    #     name: mingw
    #     state: present
    #     version: '8.1.0'


    # - name: Install ruby2.devkit
    #   win_chocolatey:
    #     name: ruby2.devkit
    #     state: present

    # - name: Install msys2
    #   win_chocolatey:
    #     name: msys2
    #     state: present

    - name: Install python virtualwrapper
      win_shell: pip install virtualenvwrapper-win
      args:
        executable: cmd

    - name: Support for Makefiles
      win_chocolatey:
        name: make
        state: present

    - name: Support for Makefiles
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install awscli
      win_chocolatey:
        name: awscli
        state: present

# choco install visualstudio2017community --package-parameters "...."
    - name: Install Visual studio 2017 community
      win_chocolatey:
        name: visualstudio2017community
        state: present
        package_params: "--norestart --wait --quiet --locale en-US --add Microsoft.VisualStudio.Workload.NativeDesktop"
#        package_params: "--allWorkloads --includeRecommended --includeOptional --passive --locale en-US"

    - name: Install dotnet35 for wix
      win_chocolatey:
        name: dotnet3.5
        state: present
      register: dotnet35_try1

    - name: Install dotnet35 for wix
      win_chocolatey:
        name: dotnet3.5
        state: present
      when: dotnet35_try1 is failed

    - name: Install Wix tool set
      win_chocolatey:
        name: wixtoolset
        state: present

    - name: Install hg
      win_chocolatey:
        name: hg
        state: present
        version: 4.6.1

    - name: Install pkgconfiglite
      win_chocolatey:
        name: pkgconfiglite
        state: present
        version: 0.28

    - name: Install wget
      win_chocolatey:
        name: wget
        state: present

    - name: Fix spotted bundler issue
      win_shell: gem update --system 3.0.2
      args:
        executable: cmd

#     Not able to execute normally
#    - name: Tune git config
#      win_shell: git config --global http.sslcainfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"
#      args:
#        executable: cmd

    - name: Tune git config
      win_command: "git config --global user.email \"gitlab@windowsrunner.local\""

    - name: Tune git config
      win_command: "git config --global user.name \"Windows Gitlab Runner Instance\""

    - name: Create gopath directory
      win_file:
        path: "C:\\gopath"
        state: directory

    - name: ENV | GOPATH
      win_environment:
        state: present
        name: GOPATH
        value: "c:\\gopath"
        level: machine

    - name: ENV | GOROOT
      win_environment:
        state: present
        name: GOROOT
        value: "c:\\tools\\go"
        level: machine

    - name: ENV | GOBIN
      win_environment:
        state: present
        name: GOBIN
        value: "c:\\tools\\go\\bin"
        level: machine



