- hosts: all

  vars_files:
    - builder_vars.yml

  tasks:
    - name: ENV | GOPATH
      win_environment:
        state: present
        name: GOPATH
        value: "c:\\gopath"
        level: user

    - name: ENV | GOROOT
      win_environment:
        state: present
        name: GOROOT
        value: "c:\\tools\\go"
        level: user

    - name: ENV | GOBIN
      win_environment:
        state: present
        name: GOBIN
        value: "c:\\tools\\go\\bin"
        level: user
