# Default values for sts-trace-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: stackstate/stackstate-trace-agent
  pullPolicy: IfNotPresent
  tag: 2.1.0

trace_agent_config_map:
    STS_API_KEY: "API_KEY"
    STS_STS_URL: "http://34.254.41.209:7077/stsAgent"
    STS_HOSTNAME: "trace-java-demo"
    STS_PROCESS_AGENT_URL: "http://34.254.41.209:7077:7077/stsAgent"
    STS_PROCESS_AGENT_ENABLED: "false"
    STS_NETWORK_TRACING_ENABLED: "true"
    STS_APM_URL: "http://34.254.41.209:7077/stsAgent"
    STS_APM_ENABLED: "true"
#    HOST_PROC: "/host/proc"
#    HOST_SYS: "/host/sys"
    STS_LOG_LEVEL: "debug"
    STS_LOG_TO_CONSOLE: "true"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8126

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
