apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: sts-agent-config
  behavior: merge
  literals:
     - STS_API_KEY=SOMEOTHER
- name: sts-clusteragent-config
  behavior: merge
  literals:
     - STS_API_KEY=SOMEOTHER2

